services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5


  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_ENGINE: postgresql+psycopg2://postgres:example@db:5432/postgres
      BASE_URL: http://localhost:8000/api/
volumes:
  db-data:
